# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Lint

on: pull_request

permissions:
  contents: read

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    name: yaml

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: GitHub action templates lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: workflow-templates
          config_data: |
            line-length: warning

      - name: Run zizmor 🌈 on actions
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          inputs: '.github/workflows/*.yml'
          advanced-security: false
          annotations: true
          min-severity: 'medium'

      - name: Run zizmor 🌈 on workflow-templates
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          inputs: 'workflow-templates/*.yml'
          advanced-security: false
          annotations: true
          min-severity: 'medium'
